name: Continuous Integration

# Triggers the workflow on push or pull request
# events but only for the "master" branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

# This workflow will download all the essential
# tools, build the application and runt the tests
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # Environment variables for testing
    env:
      DBI_DSN: dbi:Pg:dbname=mydb
      DBI_USER: myuser
      DBI_PASS: mypass
      POSTGRES_HOME: /usr/lib/postgresql/16/bin

    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Mojo & Carton
        run: |
          sudo apt install build-essential
          sudo apt install cpanminus
          sudo cpanm Mojolicious
          sudo cpanm Carton
          mojo version
          perl -v

      - name: Install PostgreSQL
        run: sudo apt install -y
          postgresql
          postgresql-client
          postgresql-contrib
          libpq-dev

      - name: Install dependencies
        run: |
          carton install

      # Needed for Test::DBIx::Class
      - name: Create symlink for postmaster
        run: |
          sudo ln -s /usr/lib/postgresql/16/bin/postgres /usr/lib/postgresql/16/bin/postmaster
          echo "/usr/lib/postgresql/16/bin" >> $GITHUB_PATH

      - name: Run Backend Tests
        run: |
          carton exec -- prove -l t/helper
          carton exec -- prove -l t
